# Generated by Django 5.0.9 on 2026-09-05 00:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlatformRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "generic_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("8.00"), max_digits=6
                    ),
                ),
                (
                    "dnd_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10.00"), max_digits=6
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_admin_campaign", models.BooleanField(default=False)),
                ("sender_id", models.CharField(max_length=11)),
                ("message", models.TextField()),
                (
                    "channel",
                    models.CharField(
                        choices=[("generic", "Generic"), ("dnd", "DND")],
                        default="dnd",
                        max_length=10,
                    ),
                ),
                (
                    "termii_campaign_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("delivered", models.PositiveIntegerField(default=0)),
                ("failed", models.PositiveIntegerField(default=0)),
                (
                    "total_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "termii_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("DELIVERED", "Delivered"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SMSLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.CharField(max_length=15)),
                (
                    "provider_msg_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("status", models.CharField(default="PENDING", max_length=20)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="campaigns.campaign",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SenderID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=11)),
                (
                    "platform_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending", "Pending"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("termii_dnd_whitelisted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sender_ids",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "name")},
            },
        ),
    ]
