# Generated by Django 5.0.9 on 2026-09-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('DELIVERED', 'Delivered'), ('PARTIAL', 'Partially delivered'), ('FAILED', 'Failed')], default='PENDING', max_length=15),
        ),
    ]
