# Generated by Django 5.0.9 on 2026-09-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_alter_campaign_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='provider',
            field=models.CharField(choices=[('termii', 'Termii'), ('sendchamp', 'Sendchamp')], default='termii', max_length=10),
        ),
    ]
