# Generated by Django 5.0.9 on 2026-09-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='provider_error',
            field=models.TextField(blank=True),
        ),
    ]
