# Generated by Django 5.0.9 on 2026-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_campaign_provider_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='provider',
            field=models.CharField(choices=[('termii', 'Termii'), ('sendchamp', 'Sendchamp'), ('kudisms', 'KudiSMS')], default='termii', max_length=10),
        ),
    ]
