# Generated by Django 5.0.9 on 2026-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_alter_campaign_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderid',
            name='provider',
            field=models.CharField(choices=[('termii', 'Termii'), ('sendchamp', 'Sendchamp'), ('kudisms', 'KudiSMS')], default='termii', max_length=10),
        ),
    ]
