# Generated by Django 5.0.9 on 2026-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0006_senderid_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='senderid',
            name='use_case',
            field=models.TextField(blank=True),
        ),
    ]
