# Generated by Django 5.0.9 on 2026-09-05 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0007_senderid_use_case'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='senderid',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='senderid',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('shared', 'Shared'), ('admin_only', 'Admin only')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='senderid',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_ids', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='senderid',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='unique_private_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='senderid',
            constraint=models.UniqueConstraint(condition=models.Q(('visibility', 'shared')), fields=('name',), name='unique_shared_name'),
        ),
        migrations.AddConstraint(
            model_name='senderid',
            constraint=models.UniqueConstraint(condition=models.Q(('visibility', 'admin_only')), fields=('name',), name='unique_admin_only_name'),
        ),
    ]
